// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mytheme.Dal;

namespace Mytheme.Migrations
{
    [DbContext(typeof(DataStorage))]
    [Migration("20191106195449_TemplateRenderWork")]
    partial class TemplateRenderWork
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Mytheme.Dal.Dto.RandomTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("RandomTables");
                });

            modelBuilder.Entity("Mytheme.Dal.Dto.TableCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("TableCategories");
                });

            modelBuilder.Entity("Mytheme.Dal.Dto.TableEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Entry")
                        .HasColumnType("TEXT");

                    b.Property<int>("LowerBound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RandomTableForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpperBound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RandomTableForeignKey");

                    b.ToTable("TableEntries");
                });

            modelBuilder.Entity("Mytheme.Dal.Dto.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Mytheme.Dal.Dto.TemplateCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("TemplateCategories");
                });

            modelBuilder.Entity("Mytheme.Dal.Dto.TemplateField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Valid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariableName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateForeignKey");

                    b.ToTable("TemplateField");
                });

            modelBuilder.Entity("Mytheme.Dal.Dto.TableEntry", b =>
                {
                    b.HasOne("Mytheme.Dal.Dto.RandomTable", "RandomTable")
                        .WithMany("Entries")
                        .HasForeignKey("RandomTableForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mytheme.Dal.Dto.TemplateField", b =>
                {
                    b.HasOne("Mytheme.Dal.Dto.Template", "Template")
                        .WithMany("Fields")
                        .HasForeignKey("TemplateForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
